doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:

            SharedValueObject:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Database/ORM/ValueObject'
                prefix: 'App\Shared\Domain\ValueObject'
                alias: App

            AuthValueObject:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Infrastructure/Database/ORM/ValueObject'
                prefix: 'App\Auth\Domain\Aggregate\Auth\ValueObject'
                alias: App
            AuthEntity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Infrastructure/Database/ORM/Entity'
                prefix: 'App\Auth\Domain\Aggregate\Auth\Entity'
                alias: App

            ProductEntity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Domain/Aggregate/Product/Entity'
                prefix: 'App\Product\Domain\Aggregate\Product\Entity'
                alias: App

            ProductCategoryEntity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Domain/Aggregate/Product/Category/Entity'
                prefix: 'App\Product\Domain\Aggregate\Product\Category\Entity'
                alias: App
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
